// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2jdMCTBTYkV9TUxriOsN9q3YrjwXV_Cs',
    appId: '1:821923521593:web:2f2dfbc2b8b0875ba8d9e8',
    messagingSenderId: '821923521593',
    projectId: 'study-flow-45cd8',
    authDomain: 'study-flow-45cd8.firebaseapp.com',
    storageBucket: 'study-flow-45cd8.firebasestorage.app',
    measurementId: 'G-94MZMGNQ04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD54pI6tUVZtfRghsU-i1xXadImoiz58o0',
    appId: '1:821923521593:android:2c468fc06aec0a1ea8d9e8',
    messagingSenderId: '821923521593',
    projectId: 'study-flow-45cd8',
    storageBucket: 'study-flow-45cd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFEc9AOOp83hynwCWE-mvpfTEyN2hUxFc',
    appId: '1:821923521593:ios:425d094967fbf5e8a8d9e8',
    messagingSenderId: '821923521593',
    projectId: 'study-flow-45cd8',
    storageBucket: 'study-flow-45cd8.firebasestorage.app',
    iosBundleId: 'com.example.studyFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFEc9AOOp83hynwCWE-mvpfTEyN2hUxFc',
    appId: '1:821923521593:ios:425d094967fbf5e8a8d9e8',
    messagingSenderId: '821923521593',
    projectId: 'study-flow-45cd8',
    storageBucket: 'study-flow-45cd8.firebasestorage.app',
    iosBundleId: 'com.example.studyFlow',
  );
}
